### ISSUE TITLE
Implement `Debug` for `magic::Cookie`

### ISSUE THREAD

**Issue by koutheir** [robo9k/rust-magic#21]
This is useful for testing, because the `std::result::Result::unwrap_err()` method and the `assert_eq!()` macro both require the success value to implement `Debug`. This is not a breaking change.

**Comment by robo9k** [comment]
What would you expect as `Debug` impl output?

The wrapped `Magic` FFI handle is opaque and probably not useful on its own.
Tracking set flags and loaded databases might be too much overhead just for debug output and tricky with e.g. #20

**Comment by koutheir** [comment]
> What would you expect as Debug impl output?

Nothing special really, anything that would **identify** a particular instance of `magic::Cookie` is enough as a start, even if it is not useful to link the cookie to the loaded data bases. The FFI handle seems appropriate in this case. If a more expressive `Debug` implementation proves useful, then that can be changed later.
